services:
  postgres:
    image: postgres:16.3-alpine
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=bookstore
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d bookstore -U admin" ]
      interval: 10s
      timeout: 5s
      retries: 5