logging:
    level:
        org:
            springframework:
                jdbc: TRACE
                transaction: DEBUG
bookstore:
    runner:
        enabled: true
    audit:
        enabled: true
audit:
    server:
        url: http://localhost:9090